### ISSUE TITLE
Can't Build On OCaml 4.02.1

### ISSUE THREAD

**Issue by fribeiro1** [mfp/ocaml-stomp#1]
I am getting an error when building on OCaml 4.02.1:

```
*** omake: reading OMakefiles
--- Checking for ocamlfind... (found /root/.opam/4.02.1/bin/ocamlfind)
--- Checking for ocamlc.opt... (found /root/.opam/4.02.1/bin/ocamlc.opt)
--- Checking for ocamlopt.opt... (found /root/.opam/4.02.1/bin/ocamlopt.opt)
--- Checking whether ocamlc understands the "z" warnings... (yes)
*** omake: finished reading OMakefiles (0.06 sec)
--- Checking if ocamldep understands -modules... (yes)
- build . mq_rabbitmq.cmo                                                      
+ ocamlfind ocamlc -package lwt,lwt.unix,extlib,cryptokit,threads -g -thread -bin-annot -w +a-4-6-9-27..29-32..99 -warn-error +a-4-6-7-9-18-27..29-32..99 -g -dtypes -I . -c mq_rabbitmq.ml
File "mq_rabbitmq.ml", line 13, characters 12-25:
Warning 3: deprecated: String.create====                       ] 00047 / 00073
Use Bytes.create instead.
File "mq_rabbitmq.ml", line 25, characters 8-42:
Warning 3: deprecated: String.set
Use Bytes.set instead.
File "mq_rabbitmq.ml", line 1:
Error: Some fatal warnings were triggered (2 occurrences)
*** omake: 47/73 targets are up to date                                        
*** omake: failed (1.08 sec, 13/13 scans, 6/11 rules, 32/121 digests)
*** omake: targets were not rebuilt because of errors:                         
   mq_rabbitmq.cmo
      depends on: mq_rabbitmq.ml
```

Please advise.

**Comment by mfp** [comment]
On Tue, Feb 17, 2015 at 01:39:10PM -0800, Fernando Ribeiro wrote:

> I am getting an error when building on OCaml 4.02.1:
> 
> `**\* omake: reading OMakefiles
> --- Checking for ocamlfind... (found /root/.opam/4.02.1/bin/ocamlfind)
> --- Checking for ocamlc.opt... (found /root/.opam/4.02.1/bin/ocamlc.opt)
> --- Checking for ocamlopt.opt... (found /root/.opam/4.02.1/bin/ocamlopt.opt)
> --- Checking whether ocamlc understands the "z" warnings... (yes)
> **\* omake: finished reading OMakefiles (0.06 sec)
> --- Checking if ocamldep understands -modules... (yes)
> - build . mq_rabbitmq.cmo  
> - ocamlfind ocamlc -package lwt,lwt.unix,extlib,cryptokit,threads -g -thread -bin-annot -w +a-4-6-9-27..29-32..99 -warn-error +a-4-6-7-9-18-27..29-32..99 -g -dtypes -I . -c mq_rabbitmq.ml
>   File "mq_rabbitmq.ml", line 13, characters 12-25:
>   Warning 3: deprecated: String.create====                       ] 00047 / 00073
>   Use Bytes.create instead.
>   File "mq_rabbitmq.ml", line 25, characters 8-42:
>   Warning 3: deprecated: String.set
>   Use Bytes.set instead.
>   File "mq_rabbitmq.ml", line 1:
>   Error: Some fatal warnings were triggered (2 occurrences)
>   **\* omake: 47/73 targets are up to date  
>   **\* omake: failed (1.08 sec, 13/13 scans, 6/11 rules, 32/121 digests)
>   **\* omake: targets were not rebuilt because of errors:  
>   mq_rabbitmq.cmo
>     depends on: mq_rabbitmq.ml`
> 
> Please advise.

I cannot test it right now, but could you change line 8 in the OMakefile to

```
OCAMLFLAGS    = -g -thread -bin-annot -w +a-4-6-9-27..29-32..99 -warn-error +a-3-4-6-7-9-18-27..29-32..99
                                                                            =====
```

?

Will try to address this properly (i.e., by switching to Bytes) when I have
the time.

## 

Mauricio Fern�ndez

**Comment by fribeiro1** [comment]
That did the trick, thanks!
